swagger: '2.0'
info:
  title: Mein API RESTful
  version: 1.0.0
basePath: /api/v1
schemes:
  - https
consumes:
  - application/json
produces:
  - application/json
paths:
  /users:
    get:
      summary: Ruft die Liste der Benutzer ab
      responses:
        '200':
          description: Erfolg
          schema:
            type: array
            items:
              $ref: '#/definitions/User'
    post:
      summary: Username erstellen
      parameters:
        - name: user
          in: body
          description: Username erstellen
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '201':
          description: erfolgreich erstellt
          schema:
            $ref: '#/definitions/User'
  /users/{id}:
    get:
      summary: Ruft die Liste der Benutzer ab
      parameters:
        - name: id
          in: path
          description: ID von User
          required: true
          type: integer
      responses:
        '200':
          description: Erfolg
          schema:
            $ref: '#/definitions/User'
    put:
      summary: Aktualisieren Sie einen vorhandenen Benutzer
      parameters:
        - name: id
          in: path
          description: Benutzer-ID
          required: true
          type: integer
        - name: user
          in: body
          description: Benutzer aktualisiert
          required: true
          schema:
            $ref: '#/definitions/User'
      responses:
        '200':
          description: Aktualisierung erfolgreich
          schema:
            $ref: '#/definitions/User'
definitions:
  User:
    type: object
    properties:
      id:
        type: integer
      name:
        type: string
      email:
        type: string
